# refer https://eksctl.io/usage/vpc-ip-family/?h=ipv6
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: testeks-ipv6
  region: ap-northeast-1
  version: "1.24"

kubernetesNetworkConfig:
  ipFamily: IPv6

# required by ipv6
iam:
  withOIDC: true

# required by ipv6, use default version
addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy

vpc:
  subnets:
    public:
      cn-northeast-1c: {id: subnet-111111111111}
      cn-northeast-1a: {id: subnet-222222222222}
      cn-northeast-1d: {id: subnet-333333333333}
    private:
      cn-northeast-1c: {id: subnet-444444444444}
      cn-northeast-1a: {id: subnet-555555555555}
      cn-northeast-1d: {id: subnet-666666666666}

#nodeGroups:  unmanaged node group does not support IPv6 currently
managedNodeGroups:
  - name: ng-test
    instanceType: m6a.large
    desiredCapacity: 1
    volumeSize: 50
    volumeType: gp3
    privateNetworking: true
    ssh:
        publicKeyPath: ~/.ssh/id_rsa.pub
    labels:
        role: workers
        clusterName: testeks-ipv6
        clusterNg: ng-test

